import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { readFile, rm, writeFile } from "node:fs/promises";

// Use a non-default port so the test never collides with the user's own
// `bun run dev` (which binds 4321).
const PORT = 4399;
const BASE = `http://127.0.0.1:${PORT}`;
const READY_TIMEOUT_MS = 120_000;

const scaffoldDir = new URL("..", import.meta.url).pathname;
const workerDir = `${scaffoldDir}worker`;
const indexPath = `${workerDir}/index.js`;
const heyPath = `${workerDir}/hey.js`;

const HEY_HANDLER = `// Test-only handler injected by test/dev-smoke.test.ts. Removed afterwards.
export async function handleHey() {
  return new Response('Hello!', {
    status: 200,
    headers: { 'Content-Type': 'text/plain' },
  });
}
`;

const INDEX_WITH_HEY = `// Test-only worker entry generated by test/dev-smoke.test.ts.
// Mirrors worker/index.js but with a /~/hey route wired up. The error contract
// is imported from the real worker/problem.js rather than duplicated, so these
// tests fail if the shipped contract changes.
import { handleHey } from './hey.js';
import { problem } from './problem.js';

const ROUTES = {
  '/~/hey': { handler: handleHey, description: 'Hello World' },
};

export default {
  async fetch(request, env, ctx) {
    const pathname = new URL(request.url).pathname;
    const route = Object.entries(ROUTES).find(([prefix]) => pathname.startsWith(prefix));
    if (route) {
      const [, { handler, description }] = route;
      try {
        return await handler(request, ctx);
      } catch (error) {
        console.error(\`Error in \${description}:\`, error);
        return problem({
          status: 500,
          code: 'internal_error',
          title: 'Internal Server Error',
          detail: \`The \${description} handler threw while processing this request.\`,
          resolution: 'Retry once; if it persists the endpoint is broken and retrying will not help.',
        });
      }
    }
    return problem({
      status: 404,
      code: 'route_not_found',
      title: 'Not Found',
      detail: \`No worker route is registered for \${pathname}.\`,
      resolution: 'Only paths under /~/ reach this worker. Site pages are served as static assets — see /sitemap-index.xml for what exists.',
    });
  }
};
`;

let dev: ReturnType<typeof Bun.spawn> | null = null;
let originalIndex: string | null = null;

async function waitForReady(timeoutMs: number) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const r = await fetch(BASE + "/", { signal: AbortSignal.timeout(3_000) });
      if (r.status === 200) return;
    } catch {}
    await Bun.sleep(750);
  }
  throw new Error(`dev server not ready on ${BASE} within ${timeoutMs}ms`);
}

async function teardown() {
  dev?.kill();
  if (originalIndex !== null) {
    await writeFile(indexPath, originalIndex);
    originalIndex = null;
  }
  if (existsSync(heyPath)) {
    await rm(heyPath);
  }
}

beforeAll(async () => {
  // The shipped scaffold has no active /~/* routes. Inject a `/~/hey` route
  // for the duration of the test by writing a temporary worker/hey.js and
  // overwriting worker/index.js to wire it up; teardown restores both.
  originalIndex = await readFile(indexPath, "utf8");
  await writeFile(heyPath, HEY_HANDLER);
  await writeFile(indexPath, INDEX_WITH_HEY);

  // `bun run preview` already builds and passes --local --ip 127.0.0.1; only
  // override the port here so the test never collides with `bun run dev`.
  dev = Bun.spawn(
    ["bun", "run", "preview", "--", "--port", String(PORT)],
    {
      cwd: scaffoldDir,
      stdout: "inherit",
      stderr: "inherit",
      env: { ...process.env, BROWSER: "none", CI: "1", NODE_ENV: "production" },
    },
  );

  try {
    await waitForReady(READY_TIMEOUT_MS);
  } catch (e) {
    await teardown();
    throw e;
  }
}, READY_TIMEOUT_MS + 10_000);

afterAll(teardown);

// Astro is configured with `trailingSlash: "always"`, so all non-root paths
// must end in `/` — without the slash Astro's dev server intercepts with a
// "did you mean .../?" 404 page.

describe("scaffold preview server (bun run preview) smoke", () => {
  test("/~/hey/ is served by the injected worker handler", async () => {
    const r = await fetch(BASE + "/~/hey/");
    expect(r.status).toBe(200);
    expect(r.headers.get("content-type") ?? "").toContain("text/plain");
    expect((await r.text()).trim()).toBe("Hello!");
  });

  test("homepage renders as static HTML", async () => {
    const r = await fetch(BASE + "/");
    expect(r.status).toBe(200);
    expect(r.headers.get("content-type") ?? "").toContain("text/html");
  });

  test("unknown path returns a 404", async () => {
    // wrangler's run_worker_first restricts the worker to /~/* and
    // not_found_handling = "404-page" serves the prerendered 404.astro
    // (text/html). This unmatched path never reaches the worker; the asset
    // layer handles it, so we assert the 404 status here.
    const r = await fetch(BASE + "/no-such-page-xyz/");
    expect(r.status).toBe(404);
  });

  test("/404/ renders the prerendered 404.astro page", async () => {
    const r = await fetch(BASE + "/404/");
    expect(r.headers.get("content-type") ?? "").toContain("text/html");
    const body = await r.text();
    expect(body).toContain("404");
    expect(body).toContain("Page not found");
  });

  test("the 404 page gives agents somewhere to go next", async () => {
    // A bare "not found" leaves an agent with no recovery path. The page must
    // point at surfaces that actually resolve, so a stale link is survivable.
    const body = await fetch(BASE + "/404/").then((r) => r.text());
    expect(body).toContain("/sitemap-index.xml");
    expect(body).toContain("/llms.txt");

    for (const href of ["/sitemap-index.xml", "/llms.txt"]) {
      const r = await fetch(BASE + href);
      expect(r.status).toBe(200);
    }
  });

  test("an unmatched worker route returns application/problem+json", async () => {
    // The /~/* routes are the site's only programmatic surface. An agent
    // probing it should get a typed body with a code it can branch on, not
    // a plain-text "Not Found".
    const r = await fetch(BASE + "/~/no-such-route/");
    expect(r.status).toBe(404);
    expect(r.headers.get("content-type") ?? "").toContain("application/problem+json");

    const body = await r.json();
    expect(body.code).toBe("route_not_found");
    expect(body.status).toBe(404);
    expect(typeof body.detail).toBe("string");
    expect(typeof body.resolution).toBe("string");
  });

  test("the homepage carries Organization identity JSON-LD", async () => {
    // Agents use this to verify what the site is and who runs it without
    // parsing marketing copy.
    const body = await fetch(BASE + "/").then((r) => r.text());
    const blocks = [...body.matchAll(
      /<script type="application\/ld\+json">(.*?)<\/script>/gs,
    )].map((m) => JSON.parse(m[1]));

    const types = blocks.map((b) => b["@type"]);
    expect(types).toContain("Organization");
    expect(types).toContain("WebSite");

    const org = blocks.find((b) => b["@type"] === "Organization");
    expect(org.name).toBeTruthy();
    expect(org.url).toBeTruthy();
  });
});
